helloVuln: shellcodeDemo.c
#	@echo "-g: GDB Debug flag enabled"
#	@echo "-z execstack: DEP disabled"
#	@echo "-fno-stack-protector: Stack smashing protection disabled"
#	@echo 
	gcc -g -m32 -no-pie -z execstack -fno-stack-protector -o shellcodeDemo shellcodeDemo.c
